Removed Gemspec/DateAssignment
No longer supported by RuboCop as of Version 1.31.0. By removing this
cop, the following error will go away:

    Error: The `Gemspec/DateAssignment` cop has been removed. Please
    use `Gemspec/DeprecatedAttributeAssignment` instead. (obsolete
    configuration found in config/ruby.yml, please update it)